services:
  gateway-service:
    build:
      context: ./backend/gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - MONGO_URI=mongodb+srv://cafe_go_db:ulA7hof1EcajUPYm@cluster0.spgu1hn.mongodb.net/?appName=Cluster0
      - FIREBASE_ADMIN_CREDENTIALS=./src/config/firebase-admin-key.json
      - STOCK_SERVICE_URL=http://stock-service:3001
      - IDENTITY_SERVICE_URL=https://identity-service-one.vercel.app
      - KITCHEN_SERVICE_URL=https://kitchen-service-production-58ff.up.railway.app
      - NOTIFICATION_SERVICE_URL=https://notification-service-production-565a.up.railway.app
      - REDIS_URL="rediss://default:AevEAAIncDJmNmNiYTUyZGY3NWU0MzcyYjlhYWRhODc2ZjE4ODcwZHAyNjAzNTY@assured-poodle-60356.upstash.io:6379"
      - RABBITMQ_URL=amqps://wjrnitcj:gWVGIHHBOn8ls2Y-IGhSupGOOmyeud0A@shark.rmq.cloudamqp.com/wjrnitcj
      - JWT_SECRET=cafe-go-super-secret-key-2026
    networks:
      - cafe-network
    restart: unless-stopped
    depends_on:
      - redis
      - rabbitmq
      - identity-service

  identity-service:
    build:
      context: ./backend/identity-service
      dockerfile: Dockerfile
    container_name: identity-service
    environment:
      - NODE_ENV=production
      - PORT=3004
      - MONGO_URI=mongodb+srv://cafe_go_db:ulA7hof1EcajUPYm@cluster0.spgu1hn.mongodb.net/?appName=Cluster0
      - JWT_SECRET=cafe-go-super-secret-key-2026
    networks:
      - cafe-network
    restart: unless-stopped

  stock-service:
    build:
      context: ./backend/stock-service
      dockerfile: Dockerfile
    container_name: stock-service
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGO_URI=mongodb+srv://cafe_go_db:ulA7hof1EcajUPYm@cluster0.spgu1hn.mongodb.net/?appName=Cluster0
      - REDIS_URL="rediss://default:AevEAAIncDJmNmNiYTUyZGY3NWU0MzcyYjlhYWRhODc2ZjE4ODcwZHAyNjAzNTY@assured-poodle-60356.upstash.io:6379"
      - RABBITMQ_URL=amqps://wjrnitcj:gWVGIHHBOn8ls2Y-IGhSupGOOmyeud0A@shark.rmq.cloudamqp.com/wjrnitcj
    networks:
      - cafe-network
    restart: unless-stopped
    depends_on:
      - redis
      - rabbitmq

  kitchen-service:
    build:
      context: ./backend/kitchen-service
      dockerfile: Dockerfile
    container_name: kitchen-service
    environment:
      - NODE_ENV=production
      - PORT=3002
      - MONGO_URI=mongodb+srv://cafe_go_db:ulA7hof1EcajUPYm@cluster0.spgu1hn.mongodb.net/?appName=Cluster0
      - RABBITMQ_URL=amqps://wjrnitcj:gWVGIHHBOn8ls2Y-IGhSupGOOmyeud0A@shark.rmq.cloudamqp.com/wjrnitcj
    networks:
      - cafe-network
    restart: unless-stopped
    depends_on:
      - rabbitmq

  notification-service:
    build:
      context: ./backend/notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    environment:
      - NODE_ENV=production
      - PORT=3003
      - RABBITMQ_URL=amqps://wjrnitcj:gWVGIHHBOn8ls2Y-IGhSupGOOmyeud0A@shark.rmq.cloudamqp.com/wjrnitcj
    networks:
      - cafe-network
    restart: unless-stopped
    depends_on:
      - rabbitmq

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_GATEWAY_URL=/api
        - VITE_NOTIFICATION_SERVICE_URL=/
        - VITE_FIREBASE_API_KEY=AIzaSyCnahU2p-p37GDkNgUTKJMkVNecF3Py254
        - VITE_FIREBASE_AUTH_DOMAIN=cafe-go-client.firebaseapp.com
        - VITE_FIREBASE_PROJECT_ID=cafe-go-client
        - VITE_FIREBASE_STORAGE_BUCKET=cafe-go-client.firebasestorage.app
        - VITE_FIREBASE_MESSAGING_SENDER_ID=630661940235
        - VITE_FIREBASE_APP_ID=1:630661940235:web:3a168f7b81f25bfc03730e
    container_name: cafe-frontend
    ports:
      - "80:80"
    networks:
      - cafe-network
    restart: unless-stopped
    depends_on:
      - gateway-service

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    networks:
      - cafe-network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-broker
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    ports:
      - "15672:15672" # Management UI only exposed
    networks:
      - cafe-network
    restart: unless-stopped

networks:
  cafe-network:
    driver: bridge

volumes:
  redis_data:
  rabbitmq_data:
